sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ggg\",\"password\":\"996\"},{\"id\":99, \"username\":\"mvc\",\"password\":\"156\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.22.128
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka1:2002/eureka


  instance:

    prefer-ip-address: true

    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

 
management:
  endpoints:
    web:
      exposure:
        include: refresh